#!/bin/bash
# Script to add animations to remaining stages

echo "This is a reference file - manual updates required for stages 3-5 and victory page"
echo ""
echo "STAGE 3 (Gold theme):"
echo "- Add imports: PageTransition, StageParticles, ThreeBackground"
echo "- Wrap with: <PageTransition variant='scroll-unroll'>"
echo "- Add: <ThreeBackground theme='gold' />"
echo "- Add: <StageParticles theme='gold' />"
echo ""
echo "STAGE 4 (Web theme):"
echo "- Add imports: PageTransition, StageParticles, ThreeBackground"
echo "- Wrap with: <PageTransition variant='fade'>"
echo "- Add: <ThreeBackground theme='web' />"
echo "- Add: <StageParticles theme='web' />"
echo ""
echo "STAGE 5 (Imperial theme):"
echo "- Add imports: PageTransition, StageParticles, ThreeBackground"
echo "- Wrap with: <PageTransition variant='scroll-unroll'>"
echo "- Add: <ThreeBackground theme='imperial' />"
echo "- Add: <StageParticles theme='imperial' />"
echo ""
echo "VICTORY (Victory theme):"
echo "- Add imports: PageTransition, StageParticles, ThreeBackground"
echo "- Wrap with: <PageTransition variant='fade'>"
echo "- Add: <ThreeBackground theme='victory' />"
echo "- Add: <StageParticles theme='victory' />"

